---
name: "OMDb"
guid: "a628c0da-fac5-4c7e-9d1a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-omdb.png"
version: "1.0.0"
targetAbi: "10.8.10.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Get metadata from OMDb"
description: >
  Get metadata from OMDb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Omdb.dll"
changelog: |-
  - chore(deps): update dependency xunit.runner.visualstudio to v2.4.5 (#31) @renovate
  - chore(deps): update dependency microsoft.net.test.sdk to v17.6.2 (#32) @renovate

  ### New features and improvements ###
  - chore: plugin images (#12) @h1dden-da3m0n
  - Use System.Text.Json instead of ServiceStack.Text (#3) @daullmer

  ### Tests ###
  - chore(build): update analyzers (#9) @h1dden-da3m0n
  - Use System.Text.Json instead of ServiceStack.Text (#3) @daullmer

  ### Code or Repo Maintenance ###
  - Use meta ci (#26) @crobibero
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#18) @dependabot
  - chore(deps): bump coverlet.collector from 3.0.3 to 3.1.0 (#16) @dependabot
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.10.0 to 16.11.0 (#17) @dependabot

  ### Documentation updates ###
  - chore: plugin images (#12) @h1dden-da3m0n
  - chore(ci): builds, releas drafter and more (#4) @h1dden-da3m0n

  ### Dependency updates ###
  - chore(deps): update dependency coverlet.collector to v6 (#36) @renovate
  - chore(deps): update dependency xunit to v2.4.2 (#33) @renovate
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#18) @dependabot
  - chore(deps): bump coverlet.collector from 3.0.3 to 3.1.0 (#16) @dependabot
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.10.0 to 16.11.0 (#17) @dependabot
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.9.4 to 16.10.0 (#13) @dependabot
  - chore(deps): bump coverlet.collector from 1.3.0 to 3.0.3 (#6) @dependabot
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#10) @dependabot
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.7.1 to 16.9.4 (#11) @dependabot

  ### CI & build changes ###
  - fix: meta ci workflows (#28) @h1dden-da3m0n
  - Use meta ci (#26) @crobibero
  - Update ci (#14) @h1dden-da3m0n
  - chore(build): update analyzers (#9) @h1dden-da3m0n
  - fix incorrect releas template dl link-template (#5) @h1dden-da3m0n
  - chore(ci): builds, releas drafter and more (#4) @h1dden-da3m0n
